include $(OB_REL)/etc/NGbasedefine.mk

DEST=pb_test
DEST_TYPE=BIN

DEST_SOURCES= pb_test.cpp pb_def.pb.cc
USER_LD_PATH=/data01/p0bm/users/caizj/pb_install/lib
USER_INC_PATH=/data01/p0bm/users/caizj/pb_install/include
#CALLED_SDL=sdl_def.sdl

#SDL_INC_PATH=./

USER_LIBRARIES=	protobuf \

#USER_DEFS += CDK_ENABLE_BENCHMARK
				
include $(OB_REL)/etc/NGCmake

